version: '3.8'

services:
  # Serviço da base de dados PostgreSQL
  db:
    image: postgres:latest
    container_name: cryptography_project_db
    environment:
      POSTGRES_USER: cripto-database-assignment
      POSTGRES_PASSWORD: cripto-database-assignment
      POSTGRES_DB: cripto-database-assignment
    volumes:
      - ./postgresql/cripto-db-schema-pg.sql:/docker-entrypoint-initdb.d/cripto-db-schema-pg.sql
    ports:
      - "5432:5432"

  # Serviço web (Flask + NGINX)
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cryptography_project_web
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./website:/app"
      - "./certificates:/certificates"
      #- "./certificates/Message_Userkeys:/certificates/Message_Userkeys"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    restart: on-failure
    environment:
      DATABASE_USER: cripto-database-assignment
      DATABASE_PASSWORD: cripto-database-assignment
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: cripto-database-assignment
      FLASK_APP: /app/app.py
      FLASK_ENV: development
      SSL_CERT_PATH: /certificates/server.crt
      SSL_KEY_PATH: /certificates/server.key
    command: >
      bash -c "nginx -t && service nginx start && python /app/app.py"

volumes:
  db_data:
    driver: local
