version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./myCA:/myCA
      - ./website:/app
    environment:
      - FLASK_APP=/app/app.py
    command: >
      bash -c "service nginx start && python /app/app.py"
